# scripts/generate_round_dur_optionA.py
from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import numpy as np
import pandas as pd


@dataclass(frozen=True)
class GroupLevel:
    alias: str
    columns: tuple[str, ...]


GROUP_LEVELS: tuple[GroupLevel, ...] = (
    GroupLevel("rr_sess", ("main_RR", "sessionID")),
    GroupLevel("rr_pt", ("main_RR", "participantID")),
    GroupLevel("rr", ("main_RR",)),
)


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(
        description=(
            "Generate Option A round-duration outlier stats from a baseQC file. "
            "Computes stats for all configured group levels, then applies one global "
            "preferred group level and one global preferred method."
        )
    )
    ap.add_argument("--input", required=True, help="Path to baseQC CSV generated by generate_base_qc_flags.py")
    ap.add_argument("--outdir", required=True, help="Directory for output files")
    ap.add_argument(
        "--preferred-group",
        default="rr_sess",
        choices=[g.alias for g in GROUP_LEVELS],
        help="Global preferred grouping level",
    )
    ap.add_argument(
        "--preferred-method",
        default="mad",
        choices=["mad", "iqr"],
        help="Global preferred outlier method",
    )
    ap.add_argument(
        "--mad-threshold",
        type=float,
        default=3.0,
        help="One-sided MAD z threshold for upper-tail round duration outliers",
    )
    ap.add_argument(
        "--iqr-multiplier",
        type=float,
        default=1.5,
        help="IQR multiplier for upper fence",
    )
    ap.add_argument(
        "--min-group-n",
        type=int,
        default=8,
        help="Minimum eligible rounds required for a group to be marked eligible",
    )
    return ap.parse_args()


def require_columns(df: pd.DataFrame, columns: Iterable[str]) -> None:
    missing = [c for c in columns if c not in df.columns]
    if missing:
        raise ValueError(f"Missing required columns: {missing}")


def first_nonnull(s: pd.Series):
    nonnull = s.dropna()
    return nonnull.iloc[0] if not nonnull.empty else np.nan


def encode_group_key(df: pd.DataFrame, columns: tuple[str, ...]) -> pd.Series:
    parts = []
    for c in columns:
        part = df[c].astype("string").fillna("<NA>")
        parts.append(c + "=" + part)
    return pd.Series([" | ".join(items) for items in zip(*parts)], index=df.index, dtype="string")


def mad_stats(x: pd.Series, threshold: float) -> dict[str, float]:
    vals = pd.to_numeric(x, errors="coerce").dropna()
    if vals.empty:
        return {
            "center": np.nan,
            "mad": np.nan,
            "scale": np.nan,
            "upper_threshold": np.nan,
            "out_count": 0,
        }

    center = float(vals.median())
    mad = float((vals - center).abs().median())
    scale = float(1.4826 * mad) if mad > 0 else np.nan
    upper_threshold = float(center + threshold * scale) if pd.notna(scale) else np.nan
    z = (vals - center) / scale if pd.notna(scale) and scale > 0 else pd.Series(np.nan, index=vals.index)
    out = z > threshold
    return {
        "center": center,
        "mad": mad,
        "scale": scale,
        "upper_threshold": upper_threshold,
        "out_count": int(out.fillna(False).sum()),
    }


def iqr_stats(x: pd.Series, multiplier: float) -> dict[str, float]:
    vals = pd.to_numeric(x, errors="coerce").dropna()
    if vals.empty:
        return {
            "q1": np.nan,
            "median": np.nan,
            "q3": np.nan,
            "iqr": np.nan,
            "lower": np.nan,
            "upper": np.nan,
            "out_count": 0,
        }

    q1 = float(vals.quantile(0.25))
    median = float(vals.quantile(0.50))
    q3 = float(vals.quantile(0.75))
    iqr = float(q3 - q1)
    lower = float(q1 - multiplier * iqr)
    upper = float(q3 + multiplier * iqr)
    out = vals > upper
    return {
        "q1": q1,
        "median": median,
        "q3": q3,
        "iqr": iqr,
        "lower": lower,
        "upper": upper,
        "out_count": int(out.sum()),
    }


def build_round_table(df: pd.DataFrame) -> pd.DataFrame:
    require_columns(
        df,
        [
            "roundID",
            "roundID_int",
            "participantID",
            "sessionID",
            "main_RR",
            "round_dur_s",
            "isEligibleBase",
        ],
    )

    round_df = (
        df.groupby("roundID", dropna=False)
        .agg(
            roundID_int=("roundID_int", first_nonnull),
            participantID=("participantID", first_nonnull),
            sessionID=("sessionID", first_nonnull),
            main_RR=("main_RR", first_nonnull),
            sessionType=("sessionType", first_nonnull),
            coinSet=("coinSet", first_nonnull),
            CoinSetID=("CoinSetID", first_nonnull),
            isSwap=("isSwap", first_nonnull),
            startPos=("startPos", first_nonnull),
            totalRounds=("totalRounds", first_nonnull),
            isTP2=("isTP2", first_nonnull),
            isTutorial=("isTutorial", first_nonnull),
            isIncompleteRound=("isIncompleteRound", first_nonnull),
            isPerfectRound=("isPerfectRound", first_nonnull),
            n_badDrops=("n_badDrops", first_nonnull),
            n_pinDrops=("n_pinDrops", first_nonnull),
            baseEligibilityReason=("baseEligibilityReason", first_nonnull),
            isEligibleBase=("isEligibleBase", first_nonnull),
            round_dur_s=("round_dur_s", first_nonnull),
        )
        .reset_index()
    )
    round_df["isEligibleRoundDur"] = round_df["isEligibleBase"].fillna(False).astype(bool) & round_df["round_dur_s"].notna()
    return round_df


def compute_group_level_stats(
    round_df: pd.DataFrame,
    group_levels: tuple[GroupLevel, ...],
    mad_threshold: float,
    iqr_multiplier: float,
    min_group_n: int,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    rounds = round_df.copy()
    eligible = rounds["isEligibleRoundDur"]
    stats_frames: list[pd.DataFrame] = []

    for gl in group_levels:
        group_key_col = f"roundDur_{gl.alias}_groupKey"
        rounds[group_key_col] = encode_group_key(rounds, gl.columns)

        eligible_rounds = rounds.loc[eligible].copy()
        eligible_rounds[group_key_col] = encode_group_key(eligible_rounds, gl.columns)

        grouped = eligible_rounds.groupby(list(gl.columns), dropna=False)

        meta = grouped.agg(
            group_total_n=("roundID", "size"),
            group_valid_n=("round_dur_s", lambda s: int(pd.to_numeric(s, errors="coerce").notna().sum())),
            roundDurValues=("round_dur_s", lambda s: list(pd.to_numeric(s, errors="coerce").dropna())),
        ).reset_index()

        mad_df = pd.DataFrame(list(meta["roundDurValues"].apply(lambda vals: mad_stats(pd.Series(vals), mad_threshold))))
        iqr_df = pd.DataFrame(list(meta["roundDurValues"].apply(lambda vals: iqr_stats(pd.Series(vals), iqr_multiplier))))

        stats = pd.concat([meta.drop(columns=["roundDurValues"]), mad_df.add_prefix("mad_"), iqr_df.add_prefix("iqr_")], axis=1)
        stats["group_level"] = gl.alias
        stats["group_key"] = encode_group_key(stats, gl.columns)
        stats["group_eligible"] = stats["group_valid_n"] >= min_group_n
        stats["mad_out_rate"] = stats["mad_out_count"] / stats["group_valid_n"].replace(0, np.nan)
        stats["iqr_out_rate"] = stats["iqr_out_count"] / stats["group_valid_n"].replace(0, np.nan)
        stats_frames.append(stats)

        merge_cols = list(gl.columns)
        rounds = rounds.merge(
            stats[
                merge_cols
                + [
                    "group_key",
                    "group_total_n",
                    "group_valid_n",
                    "group_eligible",
                    "mad_center",
                    "mad_mad",
                    "mad_scale",
                    "mad_upper_threshold",
                    "iqr_q1",
                    "iqr_median",
                    "iqr_q3",
                    "iqr_iqr",
                    "iqr_lower",
                    "iqr_upper",
                ]
            ].rename(
                columns={
                    "group_key": group_key_col,
                    "group_total_n": f"roundDur_{gl.alias}_n",
                    "group_valid_n": f"roundDur_{gl.alias}_validN",
                    "group_eligible": f"roundDur_{gl.alias}_eligible",
                    "mad_center": f"roundDur_mad_{gl.alias}_center",
                    "mad_mad": f"roundDur_mad_{gl.alias}_mad",
                    "mad_scale": f"roundDur_mad_{gl.alias}_scale",
                    "mad_upper_threshold": f"roundDur_mad_{gl.alias}_upper",
                    "iqr_q1": f"roundDur_iqr_{gl.alias}_q1",
                    "iqr_median": f"roundDur_iqr_{gl.alias}_median",
                    "iqr_q3": f"roundDur_iqr_{gl.alias}_q3",
                    "iqr_iqr": f"roundDur_iqr_{gl.alias}_iqr",
                    "iqr_lower": f"roundDur_iqr_{gl.alias}_lower",
                    "iqr_upper": f"roundDur_iqr_{gl.alias}_upper",
                }
            ),
            on=merge_cols + [group_key_col],
            how="left",
        )

        mad_center_col = f"roundDur_mad_{gl.alias}_center"
        mad_scale_col = f"roundDur_mad_{gl.alias}_scale"
        mad_z_col = f"roundDur_mad_{gl.alias}_z"
        mad_out_col = f"roundDur_mad_{gl.alias}_out"

        rounds[mad_z_col] = (
            pd.to_numeric(rounds["round_dur_s"], errors="coerce")
            - pd.to_numeric(rounds[mad_center_col], errors="coerce")
        ) / pd.to_numeric(rounds[mad_scale_col], errors="coerce")
        rounds[mad_out_col] = (rounds[mad_z_col] > mad_threshold).fillna(False)

        iqr_upper_col = f"roundDur_iqr_{gl.alias}_upper"
        iqr_out_col = f"roundDur_iqr_{gl.alias}_out"
        rounds[iqr_out_col] = (
            pd.to_numeric(rounds["round_dur_s"], errors="coerce")
            > pd.to_numeric(rounds[iqr_upper_col], errors="coerce")
        ).fillna(False)

    return rounds, pd.concat(stats_frames, ignore_index=True, sort=False)


def add_preferred_columns(
    round_df: pd.DataFrame,
    preferred_group: str,
    preferred_method: str,
) -> pd.DataFrame:
    rounds = round_df.copy()

    rounds["roundDur_pref_group"] = preferred_group
    rounds["roundDur_pref_method"] = preferred_method
    rounds["roundDur_pref_reason"] = f"global_preference:{preferred_group}:{preferred_method}"
    rounds["roundDur_pref_groupKey"] = rounds[f"roundDur_{preferred_group}_groupKey"]
    rounds["roundDur_pref_groupN"] = rounds[f"roundDur_{preferred_group}_n"]
    rounds["roundDur_pref_groupValidN"] = rounds[f"roundDur_{preferred_group}_validN"]
    rounds["roundDur_pref_groupEligible"] = rounds[f"roundDur_{preferred_group}_eligible"]

    if preferred_method == "mad":
        rounds["roundDur_pref_center"] = rounds[f"roundDur_mad_{preferred_group}_center"]
        rounds["roundDur_pref_scale"] = rounds[f"roundDur_mad_{preferred_group}_scale"]
        rounds["roundDur_pref_upper"] = rounds[f"roundDur_mad_{preferred_group}_upper"]
        rounds["roundDur_pref_score"] = rounds[f"roundDur_mad_{preferred_group}_z"]
        rounds["roundDur_pref_out"] = rounds[f"roundDur_mad_{preferred_group}_out"]
    else:
        rounds["roundDur_pref_center"] = rounds[f"roundDur_iqr_{preferred_group}_median"]
        rounds["roundDur_pref_scale"] = rounds[f"roundDur_iqr_{preferred_group}_iqr"]
        rounds["roundDur_pref_upper"] = rounds[f"roundDur_iqr_{preferred_group}_upper"]
        rounds["roundDur_pref_score"] = (
            pd.to_numeric(rounds["round_dur_s"], errors="coerce")
            - pd.to_numeric(rounds[f"roundDur_iqr_{preferred_group}_upper"], errors="coerce")
        )
        rounds["roundDur_pref_out"] = rounds[f"roundDur_iqr_{preferred_group}_out"]

    return rounds


def build_overall_summary(
    round_df: pd.DataFrame,
    group_stats: pd.DataFrame,
    preferred_group: str,
    preferred_method: str,
) -> pd.DataFrame:
    rows: list[dict[str, object]] = []

    eligible = round_df["isEligibleRoundDur"]

    rows.append({"section": "overall", "metric": "preferred_group", "value": preferred_group})
    rows.append({"section": "overall", "metric": "preferred_method", "value": preferred_method})
    rows.append({"section": "overall", "metric": "n_rounds_raw", "value": int(len(round_df))})
    rows.append({"section": "overall", "metric": "n_rounds_eligible_roundDur", "value": int(eligible.sum())})
    rows.append({"section": "overall", "metric": "n_rounds_pref_out", "value": int((eligible & round_df["roundDur_pref_out"].fillna(False)).sum())})
    rows.append({"section": "overall", "metric": "n_rounds_pref_kept", "value": int((eligible & ~round_df["roundDur_pref_out"].fillna(False)).sum())})

    for gl in GROUP_LEVELS:
        alias = gl.alias
        rows.append({"section": "group_level", "group_level": alias, "metric": "n_rounds_eligible_roundDur", "value": int(eligible.sum())})
        rows.append({"section": "group_level", "group_level": alias, "metric": "n_rounds_in_eligible_groups", "value": int((eligible & round_df[f"roundDur_{alias}_eligible"].fillna(False)).sum())})
        rows.append({"section": "group_level", "group_level": alias, "metric": "n_rounds_in_ineligible_groups", "value": int((eligible & ~round_df[f"roundDur_{alias}_eligible"].fillna(False)).sum())})
        rows.append({"section": "group_level", "group_level": alias, "metric": "n_mad_out", "value": int((eligible & round_df[f"roundDur_mad_{alias}_out"].fillna(False)).sum())})
        rows.append({"section": "group_level", "group_level": alias, "metric": "n_iqr_out", "value": int((eligible & round_df[f"roundDur_iqr_{alias}_out"].fillna(False)).sum())})

    for _, row in group_stats.iterrows():
        rows.append(
            {
                "section": "group_stats",
                "group_level": row["group_level"],
                "group_key": row["group_key"],
                "metric": "group_total_n",
                "value": row["group_total_n"],
            }
        )
        rows.append(
            {
                "section": "group_stats",
                "group_level": row["group_level"],
                "group_key": row["group_key"],
                "metric": "group_valid_n",
                "value": row["group_valid_n"],
            }
        )
        rows.append(
            {
                "section": "group_stats",
                "group_level": row["group_level"],
                "group_key": row["group_key"],
                "metric": "group_eligible",
                "value": row["group_eligible"],
            }
        )
        rows.append(
            {
                "section": "group_stats",
                "group_level": row["group_level"],
                "group_key": row["group_key"],
                "metric": "mad_out_count",
                "value": row["mad_out_count"],
            }
        )
        rows.append(
            {
                "section": "group_stats",
                "group_level": row["group_level"],
                "group_key": row["group_key"],
                "metric": "iqr_out_count",
                "value": row["iqr_out_count"],
            }
        )

    return pd.DataFrame(rows)


def merge_rounds_back(pin_df: pd.DataFrame, round_df: pd.DataFrame) -> pd.DataFrame:
    merge_cols = [c for c in round_df.columns if c != "roundID"]
    return pin_df.merge(round_df[["roundID"] + merge_cols], on="roundID", how="left", suffixes=("", "_round"))


def main() -> None:
    args = parse_args()
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    input_path = Path(args.input)
    pin_df = pd.read_csv(input_path)
    round_df = build_round_table(pin_df)

    round_df, group_stats = compute_group_level_stats(
        round_df=round_df,
        group_levels=GROUP_LEVELS,
        mad_threshold=args.mad_threshold,
        iqr_multiplier=args.iqr_multiplier,
        min_group_n=args.min_group_n,
    )
    round_df = add_preferred_columns(
        round_df=round_df,
        preferred_group=args.preferred_group,
        preferred_method=args.preferred_method,
    )

    augmented = merge_rounds_back(pin_df, round_df)
    overall_summary = build_overall_summary(
        round_df=round_df,
        group_stats=group_stats,
        preferred_group=args.preferred_group,
        preferred_method=args.preferred_method,
    )

    stem = input_path.stem
    augmented_path = outdir / f"{stem}_roundDur_optionA.csv"
    round_summary_path = outdir / "round_dur_optionA_round_summary.csv"
    group_stats_path = outdir / "round_dur_optionA_group_stats.csv"
    overall_summary_path = outdir / "round_dur_optionA_overall_summary.csv"
    metadata_path = outdir / "round_dur_optionA_run_metadata.json"

    augmented.to_csv(augmented_path, index=False)
    round_df.to_csv(round_summary_path, index=False)
    group_stats.to_csv(group_stats_path, index=False)
    overall_summary.to_csv(overall_summary_path, index=False)

    metadata = {
        "input": str(input_path.resolve()),
        "preferred_group": args.preferred_group,
        "preferred_method": args.preferred_method,
        "group_levels": [{g.alias: list(g.columns)} for g in GROUP_LEVELS],
        "mad_threshold": args.mad_threshold,
        "iqr_multiplier": args.iqr_multiplier,
        "min_group_n": args.min_group_n,
        "outputs": {
            "augmented_optionA": str(augmented_path.resolve()),
            "round_summary": str(round_summary_path.resolve()),
            "group_stats": str(group_stats_path.resolve()),
            "overall_summary": str(overall_summary_path.resolve()),
        },
        "notes": {
            "isEligibleRoundDur": "True when isEligibleBase is True and round_dur_s is non-null",
            "roundDur_pref_group": "Global preferred grouping level for Option A",
            "roundDur_pref_method": "Global preferred outlier method for Option A",
            "roundDur_pref_out": "Preferred Option A outlier flag for round_dur_s",
        },
    }
    metadata_path.write_text(json.dumps(metadata, indent=2), encoding="utf-8")

    print(f"Wrote: {augmented_path}")
    print(f"Wrote: {round_summary_path}")
    print(f"Wrote: {group_stats_path}")
    print(f"Wrote: {overall_summary_path}")
    print(f"Wrote: {metadata_path}")


if __name__ == "__main__":
    main()
