# ========================= merge_rpi_event_files.py =========================
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
merge_rpi_event_files.py — Merge the per-source events CSVs (BioPac and/or RNS)
that were generated by merge_ml_with_rpi_marks.py into a single combined events file.

Rules:
- If BOTH are provided and align 1:1, keep one copy of the base ML columns and
  append all label-specific columns from each source (BioPac_*, RNS_*).
- If ONLY one exists, write a combined file anyway (it will just contain that source).
- Alignment check: same number of rows and same mLTimestamp values; if mismatched,
  we align by index and emit a warning (but we do not drop rows).

Output filename:
  <base>_<device>_BioPacRNS_events.csv   (written to --out_dir if provided)
  where <base> and <device> are parsed from the input filename stem like:
  <base>_<device>_<Label>_events.csv
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Optional, Tuple
import pandas as pd
import re

from batchAlignHelpers import _is_label_col, _parse_base_and_device


def main() -> None:
    ap = argparse.ArgumentParser(description="Merge BioPac and RNS events CSVs into a single combined file")
    ap.add_argument("--biopac_events_csv", default="", help="Path to <base>_<device>_BioPac_events.csv (optional)")
    ap.add_argument("--rns_events_csv", default="", help="Path to <base>_<device>_RNS_events.csv (optional)")
    ap.add_argument("--out_dir", default="", help="Directory for output (defaults to folder of first provided file)")
    args = ap.parse_args()

    bio_path = Path(args.biopac_events_csv) if args.biopac_events_csv else None
    rns_path = Path(args.rns_events_csv) if args.rns_events_csv else None

    if not bio_path and not rns_path:
        raise SystemExit("no input provided: supply --biopac_events_csv and/or --rns_events_csv")

    # Load whichever exists
    df_bio = pd.read_csv(bio_path) if (bio_path and bio_path.exists()) else None
    df_rns = pd.read_csv(rns_path) if (rns_path and rns_path.exists()) else None

    if df_bio is None and df_rns is None:
        raise SystemExit("neither input file exists on disk")

    # Determine base/device from whichever file we have
    src_path = bio_path or rns_path
    base, device, _ = _parse_base_and_device(src_path.stem)

    # Choose out_dir
    out_dir = Path(args.out_dir) if args.out_dir else src_path.parent
    out_dir = out_dir / "BioPacRNS"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_csv = out_dir / f"{base}_{device}_BioPacRNS_events.csv"

    # If only one file, just save it under the combined name
    if df_bio is None or df_rns is None:
        (df_bio or df_rns).to_csv(out_csv, index=False)
        print(out_csv)
        return

    # Both present: try to align
    same_len = len(df_bio) == len(df_rns)
    same_ts = False
    if same_len and ("mLTimestamp" in df_bio.columns and "mLTimestamp" in df_rns.columns):
        same_ts = pd.Series(df_bio["mLTimestamp"].astype(str).values).equals(pd.Series(df_rns["mLTimestamp"].astype(str).values))

    if not same_len or not same_ts:
        print("[warn] BioPac/RNS events files differ in length or timestamps; merging by index.")

    # Build output starting from BioPac (arbitrary; base ML columns should be identical)
    out = df_bio.copy()

    # Append RNS label-specific columns, avoiding duplicates
    for col in df_rns.columns:
        if _is_label_col(col) or col.startswith("RNS_"):
            out[col] = df_rns[col]
        elif col not in out.columns:
            # Non-label columns: only add if they don't exist already
            out[col] = df_rns[col]
        else:
            # Column exists in both; if identical, skip; else keep BioPac's value and warn once
            if not out[col].equals(df_rns[col]):
                print(f"[warn] column differs between files, keeping BioPac's values: {col}")

    out.to_csv(out_csv, index=False)
    print(out_csv)


if __name__ == "__main__":
    main()

